CREATE TABLE posts (
	id INT(10) NOT NULL AUTO_INCREMENT,
	title VARCHAR(500) NULL DEFAULT NULL COLLATE 'utf8_general_ci',
	content TEXT NULL COLLATE 'utf8_general_ci',
	user_id INT(11) NULL DEFAULT NULL,
imgPath TEXT NULL COLLATE 'utf8_general_ci',
	isPublic TINYINT(4) NULL DEFAULT '0',
	createDate DATETIME NULL DEFAULT NULL,
	updateDate DATETIME NULL DEFAULT NULL,
	PRIMARY KEY (id)
)
COLLATE='utf8_general_ci'
ENGINE=MyISAM
ROW_FORMAT=DEFAULT
AUTO_INCREMENT=3